name: Resume Chatbot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black detect-secrets

    - name: Run Lint and Format Checks
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black . --check

    - name: Secrets Detection
      run: |
        detect-secrets scan > .secrets.baseline
        detect-secrets audit .secrets.baseline || true

    - name: Run OpenAI API Test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python tests/test_openai.py

    - name: Run DeepSeek API Test
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      run: python tests/test_deepseek.py
